### ISSUE TITLE
Request support for capacitor6

### ISSUE THREAD

**Issue by lvzhenbo** [Aashu-Dubey/capacitor-statusbar-safe-area#13]
Doesn't seem to be seeing errors at the moment, but there are warnings about dependencies
![image](https://github.com/Aashu-Dubey/capacitor-statusbar-safe-area/assets/32427677/11ae32ee-d2bb-4fdd-bafc-27e6fdbd65f1)

**Comment by Chirag-kalsariya** [comment]
capacitor6, Web work fine, but not in android and ios

In ios get error on console for all three method (getStatusBarHeight, getSafeAreaInsets, injectCSSVariables)
[error] - ERROR {"code":"UNIMPLEMENTED"}

**Comment by azarz** [comment]
The migration does not seem to be too troublesome. I followed the steps [here](https://capacitorjs.com/docs/updating/plugins/6-0) on a clone of the repo, and it ran without issues. However, I am not able to test if those changes worked, this is why I have not submitted a PR.

Edit: I managed to test the changes on Android and it worked. Could you test my PR #15 on iOS @Chirag-kalsariya ?

**Comment by Chirag-kalsariya** [comment]
I will test it soon, but for my project I started using this NPM package.

https://www.npmjs.com/package/capacitor-plugin-safe-area

**Comment by Aashu-Dubey** [comment]
Published with [v3.0.0](https://www.npmjs.com/package/@aashu-dubey/capacitor-statusbar-safe-area/v/3.0.0)
