### ISSUE TITLE
Swift warning on iOS 11

### ISSUE THREAD

**Issue by angelorbastos** [Aashu-Dubey/capacitor-statusbar-safe-area#4]
Hello,

I used this plugin on an Ionic app and my iOS build got a console warning upon calling `SafeAreaController.injectCSSVariables()` (see screenshot below). After a quick Google search, this seems like a problem with the Swift bindings for the plugin: any UI operations must be forced to run on the main thread with `DispatchQueue.main.sync` (or `.async`) - see [this issue's answer](https://github.com/ionic-team/capacitor/issues/841#issuecomment-426108260) for an example on how to fix it.

Just to make it clear, the issue doesn't seem to break my build (the CSS variables still work as intended), but it seems to slow down the app's process for a few secs while the error is being thrown.

![ios-bug](https://user-images.githubusercontent.com/52979198/223858494-e4cc39ff-5895-4ba8-ad5f-31ad2143d6e9.png)

Seems like a relatively simple fix, but I never touched Swift before so I thought it was better to discuss this before attempting a PR. Here are my package versions, in case it's useful:

- @ionic/angular: 6.4.2
- @capacitor/core: 4.7.0
- @angular/core: 15.1.0
- @aashu-dubey/capacitor-statusbar-safe-area: 1.1.0

Grats for the great plugin and thanks, it's really useful and I hope you get to fix this minor issue soon!

**Comment by Aashu-Dubey** [comment]
Hey @angelorbastos 👋🏼,

Thanks for the detailed issue and also for researching the solution, I had a quick look into this and it is showing the warnings, and after wrapping with `DispatchQueue.main.async` does seems to remove the warnings without affecting the result, but since the warnings were getting thrown on literally every line, I had to wrap whole function code with it.

PR #5 should close this issue.

Can you please temporarily try the branch `fix/swift-thread-warnings-4` to see if it fixes the issue for you?

```json
"@aashu-dubey/capacitor-statusbar-safe-area": "git+https://github.com/Aashu-Dubey/capacitor-statusbar-safe-area.git#fix/swift-thread-warnings-4"
```

Thanks!

**Comment by angelorbastos** [comment]
Hello again,

Tried using the new branch but I think you forgot to re-build the package on it (I kept getting a TS error saying `Cannot find module ...`). So I just applied the changes from #5 on the code inside my `node_modules` directory and tested it.

Everything works fine and I'm not getting any errors/warnings anymore!

Thanks for the quick fix, I really appreciate it!

**Comment by Aashu-Dubey** [comment]
Hey, thanks for testing it, I think regarding the error you needed to run `npx cap sync` after adding above mentioned line inside `package.json`.

But since this works after manual changes, I guess it fixes the issue then.
